### ISSUE TITLE
是否有意将服务端提取为单独的程序

### ISSUE THREAD

**Issue by DarkCWK** [Notify-ctrl/FreeKill#66]
这样在 Linux 上跑就不需要图形化界面了

**Comment by Notify-ctrl** [comment]
本来就可以不用图形界面跑服务端啊，我就是那么开服的，用`./FreeKill -s <port>`就行了

**Comment by DarkCWK** [comment]
可能是我表诉有问题, 我是想去除包含qt的客户端部分, 这样在 Linux 服务器上编译和运行会很方便

**Comment by Notify-ctrl** [comment]
其实我也编译过只含有客户端的程序，所以这个应该不难，用ifdef就好了

**Comment by DarkCWK** [comment]
期待尽早做到, 我对于C++才刚刚开始学习, 帮不到你了

**Comment by Notify-ctrl** [comment]
现在这个程度在Linux上照样可以编译，你编译试试就知道了

**Comment by DarkCWK** [comment]
并不是不能编译, 只是希望独立出来

**Comment by Notify-ctrl** [comment]
忘记哪个PR了，总之加入了只编译服务端的宏FK_SERVER_ONLY，能只编译服务端用的代码从而少安装一堆依赖
