### ISSUE TITLE
掉线后服务器仍然认定用户已登录

### ISSUE THREAD

**Issue by DarkCWK** [Notify-ctrl/FreeKill#67]
使用 Window Server 启动 FreeKill -s 9876,
用户进入后退出再次点击进入提示用户已经登陆

**Comment by DarkCWK** [comment]
似乎是偶发性, 我重启客户端后没有此情况

**Comment by DarkCWK** [comment]
目前是不能稳定复现, 用了这几天才出现一两次这个情况

**Comment by Notify-ctrl** [comment]
你也自己开服了？不如加群一起聊

**Comment by Notify-ctrl** [comment]
我看能不能创个gitter聊天群组

**Comment by DarkCWK** [comment]
啊, 又出现了, 不知道是不是进入太久会这样, 因为我刚刚在大厅挂了一段时间, 退出再进入就提示用户已登录

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: notify ***@***.***>
发送时间: Monday, March 6, 2023 2:39:05 PM
收件人: Notify-ctrl/FreeKill ***@***.***>
抄送: DarkCWK ***@***.***>; Author ***@***.***>
主题: Re: [Notify-ctrl/FreeKill] 退出大厅后服务器仍然认定用户已登录 (Issue #67)


我看能不能创个gitter聊天群组

―

**Comment by Notify-ctrl** [comment]
挂机久了掉线吧，那正常，我还没做保活机制，欢迎PR.jpg

**Comment by Notify-ctrl** [comment]
#103 已加入心跳机制
