### ISSUE TITLE
当玩家数目以及选将数目大于一定值时，会在Add Robot后报Error

### ISSUE THREAD

**Issue by barnard33-233** [Notify-ctrl/FreeKill#99]
**Describe the bug**
当玩家数目以及选将数目大于一定值时，会在Add Robot后报Error

**To Reproduce**
1. 单机启动
2. 创建房间
3. 设置玩家数目以及选将数目（我们实验得到的最低触发条件是玩家数目5，选将数目7；没有添加扩展包，查看得到的武将数目是 25 + 2 = 27 个）
4. 创建房间
5. Add Robot（其余玩家都添加为Robot），选将
6. 触发报错：
```
Room/Error occured!
./lua/server/gamelogic.lua:97:attempt to index a nil value
```

**Desktop (please complete the following information):**
 - OS: manjaro linux
 - Version: freekill 0.0.6-1 (from aur)

**Additional context**
应该是因为 gamelogic.lua 文件92行 `getGeneralsRandomly` 返回的武将数小于 `#nonlord * generalNum` ，下面的二重循环里面 table.remove 到空的 table 后返回nil，然后触发报错的

**Comment by Notify-ctrl** [comment]
这个确实是个Bug，但我懒得修了，因为在客户端是正常显示平局（其实因为错误处理流程而自动平局），总之感谢反馈

**Comment by Notify-ctrl** [comment]
欢迎发起PR帮我修一下
